CREATE OR REPLACE PACKAGE LECTURA_CEN_TRAB IS
  
  PROCEDURE V_CENTRO (PID_CENTRO IN CENTROS.idCentro%TYPE, T_CURSOR OUT Sys_Refcursor);
  PROCEDURE V_TRABAJADOR (PID_CENTRO IN CENTROS.idCentro%TYPE, T_CURSOR OUT Sys_Refcursor);
  PROCEDURE ID_TRABAJADOR (ID_TRAB IN TRABAJADORES.idTrab%TYPE, T_CURSOR OUT Sys_Refcursor);
  
END LECTURA_CEN_TRAB;
  
  
CREATE OR REPLACE PACKAGE BODY LECTURA_CEN_TRAB IS
  
PROCEDURE V_CENTRO(PID_CENTRO IN CENTROS.idCentro%TYPE, T_CURSOR OUT Sys_Refcursor) IS
BEGIN
  OPEN T_CURSOR FOR 'SELECT * INTO T_CURSOR FROM CENTROS WHERE idCentro = PID_CENTROS';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR (-22222,'Error: NO EXISTE NINGUN CENTRO CON ESE ID');
END;
  
PROCEDURE V_TRABAJADOR(PID_CENTRO IN CENTROS.idCentro%TYPE, T_CURSOR OUT Sys_Refcursor) IS
BEGIN
  OPEN T_CURSOR FOR 'SELECT * INTO T_CURSOR FROM TRABAJADORES WHERE idCentro = PID_CENTROS';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR (-22222,'Error: NO EXISTE NINGUN CENTRO CON ESE ID');
END;
 
PROCEDURE ID_TRABAJADOR (ID_TRAB IN TRABAJADORES.idTrab%TYPE, T_CURSOR OUT Sys_Refcursor) IS
BEGIN
  OPEN T_CURSOR FOR 'SELECT * INTO T_CURSOR FROM TRABAJADORES WHERE idTrab = ID_TRAB';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR (-22223, 'Error: NO EXISTE NINGUN TRABAJADOR CON ESE DNI');
END;
  
END LECTURA_CEN_TRAB;
